import DearImage from './DearImage';

import './DearImage.blank';
import './DearImage.flexLayout';
import './DearImage.from';
import './DearImage.fromExcept';
import './DearImage.gridLayout';
import './DearImage.is';
import './DearImage.isDearImage';
import './DearImage.lineLayout';
import './DearImage.loadFontFace';
import './DearImage.loadFrom';
import './DearImage.loadFromExcept';
import './DearImage.measureText';
import './DearImage.solid';
import './DearImage.text';

import './DearImage.prototype.crop';
import './DearImage.prototype.drawBackground';
import './DearImage.prototype.drawCheckeredBackground';
import './DearImage.prototype.drawForeground';
import './DearImage.prototype.fillBackground';
import './DearImage.prototype.fillForeground';
import './DearImage.prototype.flipX';
import './DearImage.prototype.flipY';
import './DearImage.prototype.reframe';
import './DearImage.prototype.rescale';
import './DearImage.prototype.resize';
import './DearImage.prototype.resizeX';
import './DearImage.prototype.resizeY';
import './DearImage.prototype.rotate';
import './DearImage.prototype.rotateClockwise';
import './DearImage.prototype.rotateCounterClockwise';
import './DearImage.prototype.saveToFileSystem';
import './DearImage.prototype.scale';
import './DearImage.prototype.scaleDownIn';
import './DearImage.prototype.scaleDownIn';
import './DearImage.prototype.scaleIn';
import './DearImage.prototype.scaleOut';
import './DearImage.prototype.scaleUpIn';
import './DearImage.prototype.scaleUpOut';
import './DearImage.prototype.toBlob';
import './DearImage.prototype.toBuffer';
import './DearImage.prototype.toDataURL';
import './DearImage.prototype.toHTMLCanvasElement';
import './DearImage.prototype.toHTMLImageElement';
import './DearImage.prototype.toImageData';
import './DearImage.prototype.toOffscreenCanvas';

import './DearImage.utils.isDataURL';
import './DearImage.utils.isURL';

export default DearImage;
